config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'user/registrations'}

  resources :projects do
    resources :tasks
  end

  get 'main/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "projects#index"
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :project
  validates :title, presence: true
	validates :completed, inclusion: { in: [true, false] }
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    before_action :authenticate_user!
    before_action :set_project
    before_action :set_task, only: [:show, :edit, :update, :destroy]
  
    def show
    end
  
    def new
      @task = @project.tasks.build
    end
  
    def create
      @task = @project.tasks.build(task_params)
      if @task.save
        redirect_to [@project, @task], notice: 'La tarea se creó correctamente.'
      else
        render :new, error: "Algo salió mal.", status: :unprocessable_entity
      end
    end
  
    def edit
    end
  
    def update
      if @task.update(task_params)
        redirect_to [@project, @task], notice: 'La tarea se actualizó correctamente.'
      else
        render :edit, error: "Algo salió mal.", status: :unprocessable_entity
      end
    end
  
    def destroy
      if @task.destroy
        redirect_to @project, notice: 'La tarea se eliminó correctamente.'
      else
        render :show, error: "Algo salió mal.", status: :unprocessable_entity
      end
    end
  
    private
  
      def set_project
        @project = current_user.projects.find(params[:project_id])
      end
  
      def set_task
        @task = @project.tasks.find(params[:id])
      end
  
      def task_params
        params.require(:task).permit(:title, :completed)
      end
  end
  

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/edit.html.erb
<div class="container mt-5">
  <div class="card">
    <div class="card-header">
      <h2 class="card-title mb-0"><%= action_name == 'new' ? 'Nueva Tarea' : 'Editar Tarea' %></h2>
    </div>
    <div class="card-body">
      <%= form_for [@project, @task] do |f| %>
        <div class="form-group">
          <%= f.label :title %>
          <%= f.text_field :title, class: 'form-control' %>
        </div>
        <br>
        <div class="form-group form-check">
          <%= f.label :completed, class: 'form-check-label' %>
          <%= f.check_box :completed, class: 'form-check-input' %>
        </div>
        <br>
        <div class="form-group">
          <%= f.submit 'Guardar', class: 'btn btn-primary' %>
          <%= link_to 'Volver', project_path(@project), class: 'btn btn-secondary ml-2' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/tasks/new.html.erb
<div class="container mt-5">
  <div class="card">
    <div class="card-header">
      <h2 class="card-title mb-0"><%= action_name == 'new' ? 'Nueva Tarea' : 'Editar Tarea' %></h2>
    </div>
    <div class="card-body">
      <%= form_for [@project, @task] do |f| %>
        <div class="form-group">
          <%= f.label :title %>
          <%= f.text_field :title, class: 'form-control' %>
        </div>
        <br>
        <div class="form-group">
          <%= f.label :completed %>
          <%= f.check_box :completed, class: 'form-check-input' %>
        </div>
        <br>
        <div class="form-group">
          <%= f.submit class: 'btn btn-primary' %>
          <%= link_to 'Volver', project_path(@project), class: 'btn btn-secondary ml-2' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/tasks/show.html.erb
<div class="container mt-5">
  <div class="card">
    <div class="card-body">
      <h2 class="card-title"><%= @task.title %></h2>
      <p class="card-text">Completada: <%= @task.completed ? 'Sí' : 'No' %></p>
      
      <div class="btn-group" role="group" aria-label="Acciones">
        <%= link_to 'Editar', edit_project_task_path(@project, @task), class: 'btn btn-secondary' %>
        <%= link_to 'Eliminar', project_task_path(@project, @task), method: :delete, data: { confirm: '¿Estás seguro?' }, class: 'btn btn-danger' %>
        <%= link_to 'Volver', project_path(@project), class: 'btn btn-secondary' %>
      </div>
    </div>
  </div>
</div>