config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'user/registrations'}

  resources :projects do
    resources :tasks
  end

  get 'main/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "projects#index"
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  has_many :tasks, dependent: :destroy
  validates :title, presence: true
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
    before_action :authenticate_user!
    before_action :set_project, only: [:show, :edit, :update, :destroy]
  
    def index
      @projects = current_user.projects
    end
  
    def show
    end
  
    def new
      @project = current_user.projects.build
    end
  
    def create
      @project = current_user.projects.build(project_params)
      if @project.save
        redirect_to @project, notice: 'El proyecto se creó correctamente.'
      else
        render :new, error: "Algo salió mal.", status: :unprocessable_entity
      end
    end
  
    def edit
    end
  
    def update
      if @project.update(project_params)
        redirect_to @project, notice: 'El proyecto se actualizó correctamente.'
      else
        render :edit, error: "Algo salió mal.", status: :unprocessable_entity
      end
    end
  
    def destroy      
      if@project.destroy
        redirect_to projects_url, notice: 'El proyecto se eliminó correctamente.'
      else
        render :show, error: "Algo salió mal.", status: :unprocessable_entity
      end
    end
  
    private
  
      def set_project
        @project = current_user.projects.find(params[:id])
      end
  
      def project_params
        params.require(:project).permit(:title)
      end
  end
  

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/edit.html.erb
<div class="container mt-5">
  <div class="card">
    <div class="card-header">
      <h2 class="card-title mb-0"><%= action_name == 'new' ? 'Nuevo Proyecto' : 'Editar Proyecto' %></h2>
    </div>
    <div class="card-body">
      <%= form_for @project do |f| %>
        <div class="form-group">
          <%= f.label :title %>
          <%= f.text_field :title, class: 'form-control' %>
        </div>
        <br>
        <div class="form-group">
          <%= f.submit class: 'btn btn-primary' %>
          <%= link_to 'Volver', projects_path, class: 'btn btn-secondary ml-2' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/projects/index.html.erb
<% if user_signed_in? %>

  <h2 class="text-center my-4">Bienvenido, <%= current_user.username %></h2>
  <div class="container">
    <div class="card my-4">
      <div class="card-header d-flex justify-content-between align-items-center">
        <h3 class="mb-0">Tus Proyectos:</h3>
        <%= link_to 'Nuevo Proyecto', new_project_path, class: 'btn btn-primary' %>
      </div>
      <div class="card-body">
        <ul class="list-group">
          <% @projects.each do |project| %>
            <li class="list-group-item d-flex justify-content-between align-items-center">
              <%= link_to project.title, project %>
              <div>
                <%= link_to 'Editar', edit_project_path(project), class: 'btn btn-secondary btn-sm mx-1' %>
                <%= link_to 'Eliminar', project, method: :delete, data: { confirm: '¿Estás seguro?' }, class: 'btn btn-danger btn-sm' %>
              </div>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
<% end %>

app/views/projects/new.html.erb
<div class="container mt-5">
  <div class="card">
    <div class="card-header">
      <h3 class="card-title mb-0"><%= action_name == 'new' ? 'Nuevo Proyecto' : 'Editar Proyecto' %></h3>
    </div>
    <div class="card-body">
      <%= form_for @project do |f| %>
        <div class="form-group">
          <%= f.label :title %>
          <%= f.text_field :title, class: 'form-control' %>
        </div>
        <br>
        <div class="form-group">
          <%= f.submit class: 'btn btn-primary' %>
          <%= link_to 'Volver', projects_path, class: 'btn btn-secondary ml-2' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/projects/show.html.erb
<div class="container mt-5">
  <div class="card my-4">
    <div class="card-header d-flex flex-column flex-md-row justify-content-between align-items-start align-items-md-center">
      <h2 class="card-title mb-0">Proyecto: <%= @project.title %></h2>
      <div class="mt-2 mt-md-0">
        <%= link_to 'Editar', edit_project_path(@project), class: 'btn btn-secondary mx-1' %>
        <%= link_to 'Eliminar', @project, method: :delete, data: { confirm: '¿Estás seguro?' }, class: 'btn btn-danger mx-1' %>
        <%= link_to 'Volver', projects_path, class: 'btn btn-secondary mx-1' %>
      </div>
    </div>
    <div class="card-body">
      <div class="d-flex flex-column flex-md-row justify-content-between align-items-start align-items-md-center">
        <h3 class="card-title mb-0">Listado de Tareas:</h3>
        <div class="mt-2 mt-md-0">
          <%= link_to 'Nueva Tarea', new_project_task_path(@project), class: 'btn btn-primary mb-3' %>
        </div>
      </div>
      <ul class="list-group">
        <% @project.tasks.each do |task| %>
          <li class="list-group-item d-flex justify-content-between align-items-center">
            <% if request.user_agent =~ /mobile/i %> <!-- Verifica si el dispositivo es móvil -->
              <%= link_to task.title, [@project, task], style: 'width: 49%;' %> <!-- Si es móvil, ancho del 40% -->
            <% else %>
              <%= link_to task.title, [@project, task], style: 'width: 75%;' %> <!-- Si no es móvil, ancho del 80% -->
            <% end %>
            <div style="<%= request.user_agent =~ /mobile/i ? 'width: 51%;' : 'width: 25%; text-align: right;' %>"> <!-- Si es móvil, ancho del 60% y texto a la derecha -->
              <%= link_to 'Editar', edit_project_task_path(@project, task), class: 'btn btn-secondary btn-sm mx-1' %>
              <%= link_to 'Eliminar', [@project, task], method: :delete, data: { confirm: '¿Estás seguro?' }, class: 'btn btn-danger btn-sm' %>
            </div>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>